[development]
address = "localhost"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
# secret_key = openssl rand -base64 32
limits = { forms = 32768 }
template_dir = "templates"

[staging]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
# secret_key = openssl rand -base64 32 
limits = { forms = 32768 }
template_dir = "templates"

[production]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "critical"
# secret_key = openssl rand -base64 32 
limits = { forms = 32768 }
template_dir = "templates"
