[package]
name = "repl"
version = "0.1.0"
authors = ["Liam Woodward <liamowoodward@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "5.0.1"
calculator = { path = "../calculator" }
